#!/usr/bin/env bash
# Script to display username, user ID, and home directory from /etc/passwd

while IFS=":" read -r username password uid gid info home shell
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
